var generated_coins = 0 // Generated coins is the total number of coins generated by the buildings
var spent_coins = 0 // Spent coins is the total number of coins spent building


//Checks if the building types exist before finding the generated coins of all buildings of the type
if instance_exists(obj_Commercial)
{
	generated_coins += obj_Commercial.coinCount;
}

if instance_exists(obj_Industrial)
{
	generated_coins += obj_Industrial.coinCount;
}


//Checks if building placement exists before finding the total number of coins spent
if instance_exists(obj_building_place)
{
	spent_coins += obj_building_place.spent_coins;
}


//show_debug_message(16 + generated_coins - spent_coins)


if(global.savecoinplayer == true) //If boolean flag for save coin is true
{
	global.coins = global.savecoins; //Coins take the value of save coins
	//Uses the starting number of coins added with the number of generated coins minus the spent coins to achieve
	//a correct coin count, without overinflating.
	global.coins = global.savecoins + generated_coins - spent_coins; 
}
else
{
	//Uses the starting number of coins added with the number of generated coins minus the spent coins to achieve
	//a correct coin count, without overinflating.
	global.coins = 16 + generated_coins - spent_coins; 
}

